### ISSUE TITLE
Hledání titulek končí v chybě

### ISSUE THREAD

**Issue by ChimiCR** [beam-kodi-addons-repository/service.subtitles.titulky.com#10]
Ahoj. Poprvé loguji na GitHub chybu, tak kdyby bylo něco špatně, omlouvám se.
Problém je v Kodi 19.0.9, instalace na Manjaro Linux, používaný doplněk Stream Cinema Comunity... Na předchozí verzi jsem pustil stream bez titulek, dal vyhledat titulky a vše ok. Vybraj jsem a koukal. Po upgradu na Matrix nefunkční a hledání titulí skončí s odkazem na log. 
Kodi.log jsem nahrál zde: https://pastebin.com/qcCqNBwr

také jsem zde našel funkci přiložení souboru, ale to nevím, jak dopadlo. Chybu hlásím poprvé, detaily a doplnění rád poskytnu... Díky, Filip

[kodi.log](https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com/files/6359482/kodi.log)

**Comment by ondrejbima** [comment]
Chybu vidim, opravim.

**Comment by ondrejbima** [comment]
Tak u me to funguje, muzes mi prosim uploadnout tvuj soubor v ``/home/filip/.kodi/addons/service.subtitles.titulky.com/resources/lib/TitulkyClient.py``

**Comment by ondrejbima** [comment]
Nebo mozna lepe, zkus stahnout ten doplnek z [releases](https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com/releases) a zkus jestli nebude fungovat.

**Comment by ChimiCR** [comment]
Zde přikládám svůj soubor: /home/filip/.kodi/addons/service.subtitles.titulky.com/resources/lib/TitulkyClient.py (musel jem ho zazipovat, nešel jinak nahrát)

Stáhnout doplněk jdu zkusit teď.

[TitulkyClient.py.zip](https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com/files/6360897/TitulkyClient.py.zip)

**Comment by ChimiCR** [comment]
Nevím, jestli jsem chytil správně, o co mě žádáš v druhém kroku, ale stáhnul jsem z releases zip pro verzi 2.0.1 Matrix. Zkusil ho nainstalovat do kodi přes funkci instalovat doplněk ze souboru .zip a skončilo to v chybě. Log přikládám zde... 
[kodi.log](https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com/files/6360957/kodi.log)

Píše to... failed due to invalid structure.
