### ISSUE TITLE
Nobody

### ISSUE THREAD

**Issue by Tuna350Z** [beam-kodi-addons-repository/service.subtitles.titulky.com#11]
Ahoj, mohl bys prosímtě zkusit najít titulky k filmu "Nobody" z 2021? Doplněk mi odmítá je najít, přitom na serveru titulky.com jsou.

**Comment by ondrejbima** [comment]
Vyhledava se podle slova Nobody a bere se jen 1. stranka vysledku, tam bohuzel tvuj vysledek neni.

**Comment by Tuna350Z** [comment]
A nejde změnit ten limit jedné stránky? Člověk se takhle nemůže dostat u takto "blbě" pojmenovaných filmů k titulkům. Zkoušel jsem i různá ruční vyhledávání, kde jsem přidával rok, ale ani to nepomohlo.

**Comment by ondrejbima** [comment]
Kdyz doprogramujes prochazeni stranek tak to urcite pujde..

**Comment by Tuna350Z** [comment]
:)
