### ISSUE TITLE
Cez KODI plugin mi titulky obcas nenajde

### ISSUE THREAD

**Issue by jancovic** [beam-kodi-addons-repository/service.subtitles.titulky.com#12]
Neviete preco mi cez Kody Plugin niekedy nenajde titulky ?
Napr. film "Nobody 2021" priamo cez web titulky.com najdem aj stiahnem, ale cez Kodi plugin nic nenajde, ani manualne...
Ale iny film napr. Tenet mi najde titulky. Jak je to mozne ?
Vsimol som si to uz davnejsie.

**Comment by ondrejbima** [comment]
Duplikatni s #11
