### ISSUE TITLE
Bazarr a titulky.com

### ISSUE THREAD

**Issue by havrancek** [beam-kodi-addons-repository/service.subtitles.titulky.com#14]
Zdravím,
zaujíma ma, či je možné použiť nejak tento addon do Bazarr-u, ktory mi bezi v dockeri, na stahovanie titulkov z titulky.com.. 
Ak nie, dal by sa spraviť plugin, ktorý by to dokázal? Je otravné stále hľadať správne titulky, keď celá vec môže byť automatizovaná... Vopred veľmi ďakujem

**Comment by beam** [comment]
Cast by asi pouzit sla, zkus kontaktovat hudecektomas2002@seznam.cz ktery se o nejakou implementaci pokousi...
