### ISSUE TITLE
CAddonInstallJob[service.subtitles.titulky.com]: The dependency on xbmc.python version 3.0.0 could not be satisfied.

### ISSUE THREAD

**Issue by aegony** [beam-kodi-addons-repository/service.subtitles.titulky.com#15]
pri instalacii doplnku titulky.com mi hadze tuto chybu:

CAddonInstallJob[service.subtitles.titulky.com]: The dependency on xbmc.python version 3.0.0 could not be satisfied.

stretol sa s tym uz niekto?

system mac os mojave, python 3.9.6

**Comment by ondrejbima** [comment]
Pouzivas verzi pro Kodi 19+ na starsim Kodi..
Bud pouzivat repositar pro Kodi < 19 nebo Kodi >= 19 https://github.com/beam-kodi-addons-repository/repository-packages
