### ISSUE TITLE
Kompatibilita s Kodi 19 - Matrix

### ISSUE THREAD

**Issue by Rohlik** [beam-kodi-addons-repository/service.subtitles.titulky.com#16]
Ahoj,
bylo by mozne add-on aktualizovat aby jej bylo mozne nainstalovat na Kodi 19?

**Comment by ondrejbima** [comment]
Davno aktualizovano, stahnout balicek muzes bud tady v releases nebo pres repositar pro Matrix.
Vice na https://github.com/beam-kodi-addons-repository/repository-packages
