### ISSUE TITLE
Kodi 17

### ISSUE THREAD

**Issue by mino182** [beam-kodi-addons-repository/service.subtitles.titulky.com#17]
Ahoj, chcel by som poprosit o radu, na kodi 17 (spmc), mi zacalo vyhadzovat pri vyhladavani titulkov chybu. Skusal som verzie 1.5.1, 1.6.1, 1.6.2. na kodi 18 to funguje normalne. Chcem sa spytat, ci je chyba u mna a mozem postnut log, alebo doplnok uz na starsich kodi nepojde? Diky.

**Comment by ondrejbima** [comment]
No, pokud si dobre pamatuju, tak mezi Kodi 17 a 18 snad nebyla zadna zmena, melo by to tedy slapat na 17 kdyz 18 jde. Klidne muzes zkusit postnout log.

**Comment by mino182** [comment]
Ahoj, sorry za odmlku, pripajam log, je tam chyba s neoverenim ssl certifikatu ak som to dobre pochopil. Diky [spmc.log](https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com/files/7577048/spmc.log)

**Comment by ondrejbima** [comment]
Jo, pochopil jsi to spravne.
Tak je potreba upravit minimalne vsechny urlopen v TitulkyClient.py o https://stackoverflow.com/a/42302755 (Python2)

**Comment by mino182** [comment]
Diky, vyskusam, dam vediet.

**Comment by mino182** [comment]
Funguje, díky. Neviem, či to bol len môj lokálny problém a či má zmysel vytvoriť PR na starú verziu, tak prosím urob ako uznáš za vhodné, upravený súbor z v1.6.2 pripájam
[TitulkyClient.zip](https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com/files/7590552/TitulkyClient.zip)

**Comment by ondrejbima** [comment]
Tohle opravovat nebudu, nevim totiz do jake miry je to starej Android tj 7.1.1 a starsi a LetsEncrypt problem.
