### ISSUE TITLE
Vypršelo mi VIP a poté co jsem ho obnovil, titulky nejdou stahovat

### ISSUE THREAD

**Issue by Piklis** [beam-kodi-addons-repository/service.subtitles.titulky.com#18]
Zdravím, mel jsem plugin na kodi, fungoval dobre, pak mi vyprselo VIP, fungovat prestal. Znova jsem VIP zaplatil, ale jiz nefunguje. Prikladam log.
[kodi.log](https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com/files/9850910/kodi.log)

**Comment by ondrejbima** [comment]
Podle logu nebylo mozne se spojit se serverem titulky.com

**Comment by Piklis** [comment]
no dobře, nějaký nápad jak mohu problém odstranit? Já už nevím na koho se obrátit.

**Comment by Piklis** [comment]
ještě jinak, to spojení se serverem titulky.com je závislé podle toho jestli mám premium účet?

**Comment by Piklis** [comment]
tak ne, ukázalo se, že chyba je jinde, https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com/issues/19
