### ISSUE TITLE
Nejde stahovat titulky do scc pokud je nainstalovaný a spuštěný plugin Netflix (castagnait)

### ISSUE THREAD

**Issue by Piklis** [beam-kodi-addons-repository/service.subtitles.titulky.com#19]
Nevím jak přesně chybu nahlásit, jestli pomůže nějaký log. Každopádně pokud je nainstalován a povolen addon Netflix, který při startu Kodi spouští nějaké "background services" tak poté nejde v scc stahovat titulky.

Logy jsem schopný dodat, pokud budu vědět jaké.

**Comment by ondrejbima** [comment]
Ja s tim z moji strany nic moc neudelam, ja proste oteviram spojeni na web server ktere skonci neuspesne.

**Comment by Piklis** [comment]
achjo, fungovalo to, a nefunguje. A řešení neexistuje. 

Alespoň jsem to zkusil.
