### ISSUE TITLE
Problém s nalezením titulků k filmům s obecným názvem

### ISSUE THREAD

**Issue by alibagil** [beam-kodi-addons-repository/service.subtitles.titulky.com#2]
Zdravím, mám problém s addonem titulky.com pro Kodi. Pokud hledám titulky pro film, který má jednoslovný a často používaný název, addon nalezne a zobrazí pouze prvních 41 výsledků, bohužel požadované titulky jsou třeba až na 150 pozici a není tedy možnost, jak se k nim dostat. Stalo se mi to teď u filmu Room (2015) a Impérium (2016). V druhém případě to nalezne pouze 41 dílů Boardwalk Empire, nic víc. Bylo by dobré zobrazit kompletní výsledky hledání, klidně 15 stran, nebo alespoň umožnit nějakým způsobem upřesnit zadání (např. rok vydaní filmu).

**Comment by ondrejbima** [comment]
- upresneni neni mozny, je to mozne jen pro premiove ucty na titulky.com
- do strankovani se mi uplne nechce, uz takhle to tvrva dlouho nez se neco ukaze, hlavne vecer kdyz se titulky.com moc nehejbou a jeste projizdet stranky, to bude kazdej mit pocit, ze to nic nedela.. ale jestli se ti chce, muzes klidne strankovani jako volitelne do nastaveni udelat :)
  Nebo donutit titulky.com aby nestrankovali, ale tak nevim o tom, ze by to slo.

**Comment by alibagil** [comment]
Bohužel to trochu přesahuje limit mých programovacích dovedností, asi o tisíc procent :-)

Jinak bych se do toho ale pustil, ten addon je super a je škoda, že nefunguje jen u omezeného počtu požadavků, těch výsledků na více stran bude přeci na titulky.com hromada. Vždyť já jsem s ním zatím hledal titulky 3x a z toho jsem ve dvou případech narazil :-(

**Comment by ondrejbima** [comment]
Ja se do strankovani opravdou poustet nechci, kdyz ted nacteni prvni stranky vyhledani trva kolem 5 sekund a to se titulky.com docela hejbou dneska. V pripade Room by to bylo teda na 40 vterin jen nahravani obsahu pred zpracovanim.

**Comment by alibagil** [comment]
Víš co, pro mě, jako uživatele, je lepší varianta, když něco trvá 40 vteřin a funguje, než 5 vteřin, ale nefunguje. Podle mého je ideální varianta ta, kterou jsi popsal, tedy volitelné nastavení s informací, že v případě zaškrtnutí se může doba hledání prodloužit.

Ale pochopím, jestli se ti do něčeho takového nechce, předpokládám ve svém volném čase, i tak si odvedl kus práce a díky ti za ní.
