### ISSUE TITLE
Stahování titulků pouze pro překladatelské a VIP účty

### ISSUE THREAD

**Issue by JoeySid** [beam-kodi-addons-repository/service.subtitles.titulky.com#8]
Ahoj,
ode dneška při stáhnutí libovolných titulek doplněk hází hlášku:

"Ke stažení titulků potřebujete
překladatelský nebo prémiový účet.
Nastavení vašeho účtu provedete na adrese..."

Mohl by ses na to prosímtě mrknout?

Děkuju

**Comment by ondrejbima** [comment]
No, to zas bude radost.. :-1:

**Comment by muti2** [comment]
Držím palce, tady se o tom baví i na titulky.com: https://www.titulky.com/?film=1&Prispevek=1366889#pr_1366945

**Comment by ondrejbima** [comment]
Tak kdyz je to cilene proti Kodi tak moc nevim jestli ma cenu to opravovat.. ja udelam krok, oni krok proti...

**Comment by JoeySid** [comment]
Dočetl jsem se, že problém je nakonci v tom odpočtu, kterej musí proběhnout v browseru (JS). To jsi fixnul přes nějakej headless viewer nebo je tam lepší způsob?

**Comment by ondrejbima** [comment]
To nebyl problem.. ja uz to mam fixnuty, jen cekam jestli z titulky.com nevzejde nejaka moznost spoluprace abychom se takhle zbytecne nepretahovali.

**Comment by JoeySid** [comment]
A v čem je teda chyba, jestil se můžu zeptat? Ono to totiž moc nevypadá, že by se chtěli domluvit...

**Comment by ondrejbima** [comment]
Stacilo upravit hlavicku v requestu na stazeni. Dam tomu jeste nejaky cas, jestli se nejak nedohodnem. Nemam problem provoz serveru nejakym zpusobem podporit, ale musi byt z me strany proveditelne a i pro ne aby to melo nejaky prinos.

**Comment by muti2** [comment]
Snad se domluvíte, držím palce.

**Comment by ondrejbima** [comment]
Vyreseno 377cd8eb0430cd7fbe4fe00bd8c09314faa4b4ca

**Comment by muti2** [comment]
Hm, tak to nejede. Dohoda s nimi asi v nedohlednu, že?

**Comment by ondrejbima** [comment]
No, ono to slo, ale dneska u nich na foru nekdo hlasil, ze nejde stahovat vubec a podle chyby byl preklep v jejich kodu, takze do toho zase dneska sahali. Presne tomu jsem se chtel vyhnout.
Ano, dohodu nevidim jako moznou. Resp. neni shoda na tom, aby uzivatele s normalnim uctem mohli stahovat.

**Comment by ondrejbima** [comment]
Doplnek nadale funguje pouze pro premium a prekladatelske ucty.
