### ISSUE TITLE
(offtopic): bazarr support

### ISSUE THREAD

**Issue by lukasmrtvy** [beam-kodi-addons-repository/service.subtitles.titulky.com#9]
Ahoj, vim, ze je to offtopic, ale myslim, ze by bylo mozny pouzit https://github.com/morpheus65535/bazarr, namisto stahovani titulek primo v Kodi ( bude to fungovat pro nejaky domaci servery, ale ne pro televize, ktery maj Kodi integrovany ).

**Comment by ondrejbima** [comment]
Uplne nerozumim otazce, ale proc bys to nemohl pouzivat? Jsi teda odkazany jen ne Opensubtitles. Pripadne, ze si dodelas podporu pro titulky.com.
